server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${td.datasource.driver-class-name}
    url: jdbc:mysql://${td.datasource.host}:${td.datasource.port}/${td.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${td.datasource.username}
    password: ${td.datasource.password}
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
  data:
    redis:
      host: ${td.redis.host}
      port: ${td.redis.port}
      password: ${td.redis.password}
      database: ${td.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: td.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #mybatis日志输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      td:
        mapper: debug
        service: info
        controller: info

td:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    user-secret-key: wx
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication
  wechat:
    appid: ${td.wechat.appid}
    secret: ${td.wechat.secret}

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '管理端'
      paths-to-match: '/**'
      packages-to-scan: td.controller.admin
    - group: '用户端'
      paths-to-match: '/**'
      packages-to-scan: td.controller.user
