td:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: reggie_takeout
    username: root
    password: 1234
  redis:
    host: 192.168.241.130
    port: 6379
    password: 123456
    database: 0

  wechat:
    appid: wx98e6a5a30f0ad550
    secret: